language: php

php:
  - 8.1

services:
  - postgresql

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source
  - yarn install

before_script:
  - psql -c 'create database app;' -U postgres
  - for i in db/*.sql; do psql -U postgres <$i; done
  - cp -v config/local.neon.travis config/local.neon
  - yarn build

script:
  - ./vendor/bin/tester -C -s --coverage coverage.xml --coverage-src app/ ./tests/

after_failure:
  # Vytiskne obsah souborů *.actual
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

after_success:
  - travis_retry php vendor/bin/php-coveralls -vvv -x coverage.xml