version: '3'

services:
  postgres:
    ports:
      - "5432:5432"
    volumes:
      - .volumes/db:/var/lib/postgresql/data:rw

  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
